Added DataReload()
RafalWojtus21/InstaScore pull request #1
Opened 2022-07-29 20:08 UTC by RafalWojtus21

2022-07-29 20:11 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +        }}
Ziomek musisz ułożyć kod bo jest źle sformatowany sformatowany

2022-08-08 19:03 UTC, MateuszW13 commented on InstaScore/Controller/ChooseDateViewController.swift
> +// nawigacja
Do usunięcia

2022-08-08 19:05 UTC, MateuszW13 commented on InstaScore/Controller/ChooseDateViewController.swift
> +    var date2 = "2022-05-03"
co do daty to lepiej skorzystać z typu Date niż ze Stringa.
Dodatkowo brakuje przypisania wyboru daty do datePickerów, żeby wybrać odpowiedni dzień

2022-08-08 19:06 UTC, MateuszW13 commented on InstaScore/Controller/ChooseDateViewController.swift
>          // Do any additional setup after loading the view.
nie chcemy komentarzy, które są zbędne

2022-08-08 19:08 UTC, MateuszW13 commented on InstaScore/Controller/ChooseDateViewController.swift
>          datePicker1.datePickerMode = .date
Wszystkie zmiany widokowe lepiej wrzucić do prywatnej metody o nazwie `setupView()`, dzięki temu później łatwiej czytać kod, bo wiesz jaka część ma się wykonać w viewDidLoad

2022-08-08 19:09 UTC, MateuszW13 commented on InstaScore/Controller/ChooseDateViewController.swift
>          datePicker1.datePickerMode = .date
Dodatkowo polecam zmienić przypisywanie datePicketrów na autolayout a nie po jest `size`

2022-08-08 19:10 UTC, MateuszW13 commented on InstaScore/Controller/ChooseDateViewController.swift
odstępy między funkcjami powinny mieć jeden enter

2022-08-08 19:14 UTC, MateuszW13 commented on InstaScore/Controller/ChooseDateViewController.swift
> +        let resultVC =  storyboard.instantiateViewController(withIdentifier: "ResultStoryBoard") as! ResultViewController
`as!` wiąże za sobą konsekwencje zcrashowania aplikacji jak jest użyte w niedobrym miejscu, dlatego swift umożliwia rozwiązywanie takich problemów przez tworzenie `guard let` albo `if let`

```suggestion
        guard let resultVC =  storyboard.instantiateViewController(withIdentifier: "ResultStoryBoard") as? ResultViewController else { return }
```


Dodatków `ResultStoryBoard` lepiej przerzucić jako statyczna zmienna w tym kontrolerze która przyjmuje tą wartość, jeżeli będziemy chcieli użyć go ponownie to wtedy korzystamy z tej statyczniej wartości a nie przypisujemy strona ponownie, więc eliminujemy możliwość pomyłki. Można też stworzyć structure ze statycznymi zmiennymi, która będzie odpowiedzialna za przypisywanie takich danych jak na przykład 
```swift
struct Constants {
    static let resultViewControllerID = "ResultStoryBoard"
}
```

2022-08-08 19:15 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
>      var matchesCount = 0
To jest nieużywane więc można to usunąć

2022-08-08 19:19 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
>      var homeTeam = [""]
The below options are the proper ways to set default value and declare type of variable inside class

```suggestion
    var homeTeam: [String] = []
```

or

```suggestion
    var homeTeam = [String]()
```

2022-08-08 19:20 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +
Staraj się nie używać nadmiernie enterów, zajmują tylko dodatkowe miejsce, przez co mniej można przeczytać

2022-08-08 19:21 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +//                Match(homeTeam: "Arsenal", score: "3-0", awayTeam: "City")
to już można usunąć

2022-08-08 19:21 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +
do usunięcia

2022-08-08 19:22 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
>          tableView.register(UINib(nibName: "MatchCell", bundle: nil), forCellReuseIdentifier: "ReusableCell")
To mi pasuje, żeby znowu dodać do setupView()

Tak samo oba stringi z 34 linijki można by było dodać do struktury Constants albo jako statyczna zmienna w tej klasie

2022-08-08 19:22 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
>  extension ResultViewController: ScoreManagerDelegate{
spacja po `ScoreManagerDelegate`

2022-08-08 19:23 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
>      func didUpdateScore(scores:[ScoreModel]){
po `:` spacja oraz po `)` tak samo spacja

2022-08-08 19:24 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
>  //MARK: - TableView
// numberofMatches

do usunięcia pare linijek niżej

2022-08-08 19:25 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
>          let cell = tableView.dequeueReusableCell(withIdentifier: "ReusableCell", for: indexPath) as! MatchCell
tutaj tak samo jak wyżej użyłbym guard let dodatkowo masz tutaj przykład gdzie `"ReusableCell"`, które zaproponowałem przypisać do statycznej zmiennej możesz użyć w dwóch miejscach używając jednego stringa

2022-08-08 19:26 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +        cell.awayTeamLabel.text = match.match_awayteam_name
nazewnictwo bardzo złe, powinno być `match.homeTeamName`

2022-08-08 19:27 UTC, MateuszW13 commented on InstaScore/Controller/ChooseDateViewController.swift
>      @IBOutlet weak var dateTF1: UITextField!
powinniśmy unikać skrótów, nazwałbym to fromDateTextField, toDateTextField albo firstDateTextField i secondDateTextField, a najlepiej to w ogóle użyć tych datePickerów

2022-08-08 19:28 UTC, MateuszW13 commented on InstaScore/Controller/ChooseDateViewController.swift
> +        resultVC.date2 = date2
te nazwy też bym zmienił na firstDate, secondDate albo fromDate - toDate

2022-08-08 19:29 UTC, MateuszW13 commented on InstaScore/Model/ScoreManager.swift
>                      self.delegate?.didUpdateScore(scores: scores)
tu powinien być tab (źle sformatowany kod)

2022-08-08 19:30 UTC, MateuszW13 commented on InstaScore/Model/ScoreManager.swift
>          if let url = URL(string: urlString){
tutaj lepiej użyć `guard let` zamiast `if let`, w if let musisz wrzucić wszystko do klamry, a w guard let pierwsza linijka skończy Ci działanie funcji, jeżeli URL nie będzie mógł być stworzony

Dodatkowo po `)` spacja

2022-08-08 19:31 UTC, MateuszW13 commented on InstaScore/Model/ScoreManager.swift
>          if let url = URL(string: urlString){
w 26 linijce już lepiej skorzystać z `if let` jeżeli linijkę niżej chcesz tego error wyprintować

2022-08-08 19:31 UTC, MateuszW13 commented on InstaScore/Model/ScoreManager.swift
> +//        let decoder = JSONDecoder()
do usunięcia

2022-08-08 19:32 UTC, MateuszW13 commented on InstaScore/Model/ScoreManager.swift
> +            // return try decoder.decode([ScoreModel].self, from: scoreData)
to też

2022-08-08 19:32 UTC, MateuszW13 commented on InstaScore/Model/ScoreModel.swift
> +struct ScoreModel : Codable {
przed `:` usunąć spację

2022-08-08 19:32 UTC, MateuszW13 commented on InstaScore/Model/ScoreModel.swift
> +//    }
żeby zmienić te brzydkie nazwy skorzystać z tego CodingKeys (patrz na dokumentacje Apple)

2022-08-09 17:49 UTC, MateuszW13 requested changes

2022-08-09 17:49 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +    var matchByCategory: [String : [ScoreModel]] = ["" : []]
to jest nieużywane, można to usunąć

2022-08-09 17:49 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
>      @IBOutlet weak var buttonStackView: UIStackView!
czy to jest gdzieś używane? jak nie to też można usunąć

2022-08-09 17:49 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +        }
To jest dosyć obciążająca pętla, a nie używasz w ogóle tego póżniej, weź to usuń włącznie z leagueArray

2022-08-09 17:49 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +        championshipMatches = matches.filter { (a) -> Bool in
zamiast `(a)` dałbym `match`, ponieważ filtrujemy po liście meczy

2022-08-09 17:49 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +            return a.league_name.contains("Ligue 2")
ogólnie to rozwiązanie ogranicza Cię do pokazania tylko tych dwóch lig (tak wiem, że z API dostajesz tylko to), problem w tym, że kod powinien być rozwiązany tak, że będzie rozszerzalny, czyli jeżeli w API by się pojawiło więcej lig to ty dalej miałbyś tylko te dwie, moja propozycja przerobienia wyglądałaby tak, żeby stworzyć Model typu MatchLeagueModel i na początku można by było przefiltrować jakie ligi są i stworzenie listy takiego modelu, dodatkowo ten model posiadałby także zmienną typu matches i była by to lista meczy dla tej ligi, co też jesteś w stanie przefiltować i dodać w odpowiednie miejsce, jak to dobrze zapakujesz to kod będzie mógł dodać wszystkie możliwe ligi w przyszłości i będzie wyglądał w porządku

2022-08-09 17:49 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +        matchesGrouped.append(championshipMatches)
apropo mojej propozycji powyżej mniej więcej zrobiłeś to co sugeruje, ale ja bym to przerobił na modele, dzięki czemu nie będziemy mieć tego league1Grouped i Championship grouped tylko będziesz coś ale matchesGrouped które będzie arrayką modeli

2022-08-09 17:49 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "ReusableCell", for: indexPath) as! MatchCell
guard let znowu

2022-08-09 17:49 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +        var awayLabel = ""
to jest zbędne, po prostu przypisz tamte rzeczy od razu do Textu od danego widoku, w tym wypadku tworzyć dodatkowe zmienne lokalne, które program musi stworzyć i po prostu nie jest to wydajne

2022-08-09 17:49 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +        tableView.reloadData()
tableView w tym miejscu jest w ogóle nie potrzebne, przechodząc do kolejnego widoku, przeładowujesz tableView z widoku który opuszczasz

2022-08-09 17:49 UTC, MateuszW13 commented on InstaScore/Model/EventModel.swift
> +}
po import enter
przed każdym `:` usunąć spację

2022-08-09 17:49 UTC, MateuszW13 commented on InstaScore/Model/EventModel.swift
> +}
Wydaje mi się, że wszystko może być `let` zamiast `var`

2022-08-09 17:49 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +        detailsVC.passDataModel.matchesGrouped = matchesGrouped
Czemu chcesz przerzucić takie trzy parametry, zamiast przerzucić do DetailViewControllera po prostu jeden mecz?

```suggestion
        detailsVC.passDataModel.match = matchesGrouped[indexPath.section][indexPath.row]
```

2022-08-10 11:32 UTC, RafalWojtus21 commented on InstaScore/Controller/ResultViewController.swift
> +        cell.awayTeamLabel.text = match.match_awayteam_name
Ale to jest nazewnictwo parametrów z API, które dokładnie się tak nazywają
<img width="530" alt="Zrzut ekranu 2022-08-10 o 13 32 04" src="https://user-images.githubusercontent.com/108489101/183890945-2c4dd777-c19d-49f4-95e2-8f4ba4b2c528.png">

2022-08-10 11:51 UTC, RafalWojtus21 commented on InstaScore/Controller/ChooseDateViewController.swift
>          let datePicker1 = UIDatePicker()
Datepicker'y są używane, jednak do debugowania, zamiast za każdym razem wybierać datę, przypisałem ją sobie na stałe.

2022-08-10 11:52 UTC, RafalWojtus21 commented on InstaScore/Controller/ChooseDateViewController.swift
>          print("Date from \(date1)")
Nie usuwam, bo to jest właśnie potrzebne do sformatowania daty wybranej z datePickera w typie Date, na typ String który potrzebny jest do URL od API.

2022-08-10 11:58 UTC, RafalWojtus21 commented on InstaScore/Controller/DetailsViewController.swift
> +        if matchesGrouped[sectionChosen][indexChosen].goalscorer.count > 0 {
Zamysł był taki, żeby nie dodawać do EventModels żadnego pustego wydarzenia, tzn. jeśli np. goalscorer jest pusty bo nie padła żadna bramka, to żeby nie dodawać pustego elementu.

2022-08-11 07:23 UTC, MateuszW13 commented on InstaScore/Controller/ChooseDateViewController.swift
> +class ChooseDateViewController: UIViewController {
enter między nimi

2022-08-11 07:23 UTC, MateuszW13 commented on InstaScore/Controller/ChooseDateViewController.swift
> +        toDate = currentDate
to wrzuć do prywatnej metody `setupView()`

2022-08-11 07:23 UTC, MateuszW13 commented on InstaScore/Constants.swift
> +    static let detailsCellNibName = "DetailsCell"
skoro mają te same nazwy to możesz zostawić jedno z nich i użyć w różnych miejsach

2022-08-11 07:23 UTC, MateuszW13 commented on InstaScore/Controller/DetailsViewController.swift
> +        guard let cell = tableView.dequeueReusableCell(withIdentifier: "DetailsCell", for: indexPath) as? DetailsCell else {
`DetailsCell` powinno być użyte ze struktury K -- `detailsCellIdentifier`

2022-08-11 07:23 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +class ResultViewController: UIViewController {
enter

2022-08-11 07:23 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +    }
takie rzeczy bym zostawił w viewDidLoad albo wrzucił do `configure()`, a `setupView()` ma za zadanie ogarnięcie wszystkich UIowych rzeczy takich jak tableView, które zostawiłeś w viewDidLoad

2022-08-11 07:23 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
>  extension ResultViewController: UITableViewDataSource{
spacja na końcu

2022-08-11 07:23 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
>          let detailsVC =  storyboard.instantiateViewController(withIdentifier: "DetailsStoryBoard") as! DetailsViewController
string do Constants

2022-08-11 07:25 UTC, MateuszW13 commented on InstaScore/Controller/ChooseDateViewController.swift
>          print("Date from \(date1)")
ale print jest niepotrzebny 😛

2022-08-11 07:26 UTC, MateuszW13 commented on InstaScore/Controller/ChooseDateViewController.swift
>          let datePicker1 = UIDatePicker()
oki

2022-08-11 07:29 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +        cell.awayTeamLabel.text = match.match_awayteam_name
Napisałem Ci tam niżej gdzie szukać jak to naprawić 

żeby zmienić te brzydkie nazwy skorzystać z tego CodingKeys (patrz na dokumentacje Apple)

2022-08-11 07:31 UTC, MateuszW13 commented on InstaScore/Controller/DetailsViewController.swift
> +        if matchesGrouped[sectionChosen][indexChosen].goalscorer.count > 0 {
Jeżeli będzie pusty to nie powinien dodać, a jak chcesz mieć pewność to możesz map zamienić na compactMap, on działa tak, że jeżeli coś w mapie jest nilem to on tego nie doda

2022-08-11 08:15 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +    var groupedDictionary: [String: [ScoreModel]]?
Chyba tego nie potrzebujesz wystarczy Ci lokalna zmienna z funkcji, ponieważ poza funkcją nigdzie tego nie używasz

2022-08-11 08:15 UTC, MateuszW13 commented on InstaScore/Model/ScoreManager.swift
> +        }
to może być w jednej linijce

2022-08-11 08:15 UTC, MateuszW13 commented on InstaScore/View/DetailsCell.swift
> +//        minuteLabel.minimumScaleFactor = 1
do usunięcia

2022-08-11 08:15 UTC, MateuszW13 commented on InstaScore/View/DetailsCell.swift
> +
zbędne entery

2022-08-11 08:15 UTC, MateuszW13 commented on InstaScore/View/DetailsCell.swift
> +
Czy to jest potrzebne?

2022-08-11 08:15 UTC, MateuszW13 commented on InstaScore/View/MatchCell.swift
> +        timeLabel.font = UIFont.boldSystemFont(ofSize: 12)
to możesz ustawić w storyboardzie

2022-08-11 10:04 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
>      @IBOutlet weak var buttonStackView: UIStackView!
??

2022-08-11 10:06 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
>          groupedDictionary = Dictionary(grouping: matches) { (league) -> String in
to też wystarczy ze będzie lokalnie w funkcji tworzone, nie potrzebnie jest to w VC przetrzymywane

2022-08-11 10:08 UTC, MateuszW13 commented on InstaScore/Model/ScoreModel.swift
> +    let matchLive: String // 1-live, 0-finished
to byś mógł zamienić na Codable Enuma typu Int

2022-08-11 10:12 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
> +    var groupedDictionary: [String: [ScoreModel]]?
tutaj zaznaczyłem tylko `groupedDictionary` a pokazuje 4 ostatnie linijki i chodziło mi, żeby lokalnie tylko to `groupedDictionary` wrzucić tam do funkcji

2022-08-11 10:14 UTC, MateuszW13 commented on InstaScore/Controller/DetailsViewController.swift
> +    func setupTableView() {
fajnie, jakby te metody były private, to oznacza, że z pozycji innego pliku gdzie inizjalizujesz DetailViewController ta metoda będzie niewidoczna do użycia, ponieważ ty chcesz ją użyć tylko wewntątrz tej klasy

2022-08-11 10:14 UTC, MateuszW13 commented on InstaScore/Controller/DetailsViewController.swift
> +    func eventModelsSetup() {
tutaj tak samo z tym `private`

2022-08-11 11:12 UTC, MateuszW13 commented on InstaScore/Model/ScoreModel.swift
> +    let matchLive: String
powinieneś móc z tego zrobić Enuma typu 
```
enum MatchState: String, Codable {
   case live = "0"
   case finished = "1"
}

```

i potem w apce nie przypisywać, że coś jest równe 1 tylko coś jest równe .live albo .finished

Spróbuj coś takiego

2022-08-11 11:54 UTC, MateuszW13 commented on InstaScore/Controller/ResultViewController.swift
>              }
lepiej użyć switch niż if, jest bardziej elegancko i wydajniej

2022-08-11 12:07 UTC, MateuszW13 approved these changes

2022-08-11 12:09 UTC, merged